// thinking-orbs-mega/ports/solid/src/components/Header.tsx
import { For } from 'solid-js';
import type { Theme } from '../hooks/useTheme';
import { ThinkingOrb } from '../ThinkingOrb';
import { GitHubIcon, XIcon } from './icons';

function SocialDropdown(props: {
  icon: () => any;
  links: { name: string; url: string; tooltip?: string }[];
  hoverClass: string;
}) {
  return (
    <div class={`group relative flex items-center h-9 w-9 transition-all duration-[400ms] ease-[cubic-bezier(0.175,0.885,0.32,1.2)] bg-(--icon-btn-bg) hover:bg-(--icon-btn-hover) rounded-full overflow-hidden hover:overflow-visible [&_svg]:fill-(--icon-btn-fill) [&_svg]:opacity-60 hover:[&_svg]:opacity-100 ${props.hoverClass}`}>
      <div class="w-9 h-9 shrink-0 flex items-center justify-center absolute left-0 top-0 pointer-events-none z-10">
        {props.icon()}
      </div>
      <div class="absolute left-9 flex items-center gap-3 opacity-0 group-hover:opacity-100 transition-opacity duration-200 delay-0 group-hover:delay-75 whitespace-nowrap pr-3.5">
        <For each={props.links}>{(link) => (
          <div class="relative group/link inline-flex items-center">
            <a
              href={link.url}
              target="_blank"
              rel="noopener noreferrer"
              class="text-[12px] font-medium text-(--subtitle-color) hover:text-(--title-color) transition-colors py-1"
            >
              {link.name}
            </a>
            {link.tooltip && (
              <div class="absolute left-1/2 -translate-x-1/2 top-[calc(100%+4px)] opacity-0 translate-y-[-4px] scale-95 group-hover/link:opacity-100 group-hover/link:translate-y-0 group-hover/link:scale-100 transition-all duration-250 ease-[cubic-bezier(0.175,0.885,0.32,1.2)] pointer-events-none z-30 whitespace-nowrap bg-(--icon-btn-hover) backdrop-blur-md border border-[rgba(255,255,255,0.12)] text-[10px] font-medium text-(--title-color) px-2.5 py-0.5 rounded-[6px] shadow-[0_8px_20px_rgba(0,0,0,0.4)]">
                <div class="absolute -top-[4.5px] left-1/2 -translate-x-1/2 w-2 h-2 rotate-45 bg-(--icon-btn-hover) border-t border-l border-[rgba(255,255,255,0.12)]" />
                <span class="relative z-10">{link.tooltip}</span>
              </div>
            )}
          </div>
        )}</For>
      </div>
    </div>
  );
}

export function Header(props: {
  theme: Theme;
  onToggleTheme: () => void;
}) {
  return (
    <header class="relative w-full flex flex-col items-center justify-end pt-12 pb-8 text-center max-sm:pt-14 max-sm:pb-6">
      <nav class="absolute top-4 right-0 flex items-center gap-4 max-sm:top-3" aria-label="External links">
        <SocialDropdown 
          icon={() => <GitHubIcon />} 
          hoverClass="hover:w-[172px]"
          links={[
            { name: 'SolidJS Port', url: 'https://github.com/Mvkweb/solid-thinking-orbs' },
            { name: 'Original', url: 'https://github.com/Jakubantalik/thinking-orbs' }
          ]} 
        />
        <SocialDropdown 
          icon={() => <XIcon />} 
          hoverClass="hover:w-[182px]"
          links={[
            { name: 'Mvkweb', url: 'https://x.com/mvkweb' },
            { name: 'Jakub', url: 'https://x.com/jakubantalik', tooltip: '(Original Creator)' },
            { name: 'Alex', url: 'https://x.com/a_brinza', tooltip: '(Creator)' }
          ]} 
        />
      </nav>

      {/* Sleek Live-Orb Hero Icon Card */}
      <div class="relative flex flex-col items-center group cursor-pointer mb-4" aria-hidden="true">
        <div class="w-[84px] h-[84px] rounded-[24px] bg-(--hero-surface) border border-[rgba(255,255,255,0.08)] shadow-[0_12px_32px_rgba(0,0,0,0.35)] flex items-center justify-center relative overflow-hidden transition-all duration-500 ease-[cubic-bezier(0.175,0.885,0.32,1.2)] group-hover:scale-105 group-hover:border-[rgba(255,255,255,0.18)] group-hover:shadow-[0_16px_40px_rgba(0,0,0,0.5)]">
          <div class="absolute inset-0 bg-gradient-to-b from-[rgba(255,255,255,0.06)] to-transparent pointer-events-none z-10" />
          <ThinkingOrb state="hypercube" size={64} style={{ width: '62px', height: '62px' }} />
        </div>
      </div>

      <h1 class="text-[26px] font-semibold leading-[34px] tracking-tight text-(--title-color) mb-1">
        solid-thinking-orbs
      </h1>
      <p class="text-sm font-normal leading-[22px] text-(--subtitle-color) opacity-65 max-w-[500px]">
        SolidJS port and fork of Jakub Antalík's thinking-orbs, adding new custom states and expanded engine modes
      </p>
    </header>
  );
}

// thinking-orbs-mega/ports/react-native-views/demo/components/Header.tsx
import React from 'react';
import type { Theme } from '../hooks/useTheme';
import { GitHubIcon, XIcon } from './icons';

const iconBtnClass = 'flex items-center justify-center size-9 border-none rounded-full bg-(--icon-btn-bg) text-inherit cursor-pointer no-underline transition-[background-color] duration-200 [-webkit-tap-highlight-color:transparent] hover:bg-(--icon-btn-hover) focus-visible:outline-2 focus-visible:outline-(--icon-btn-outline) focus-visible:outline-offset-2 [&_svg]:block [&_svg]:shrink-0 [&_svg]:fill-(--icon-btn-fill) [&_svg]:opacity-60 [&_svg]:transition-opacity [&_svg]:duration-200 hover:[&_svg]:opacity-100';

export function Header({
  theme: _theme,
  onToggleTheme: _onToggleTheme,
  debug,
  onToggleDebug,
  bigChips,
  onToggleBigChips,
  smallAll,
  onToggleSmallAll,
}: {
  theme: Theme;
  onToggleTheme: () => void;
  debug: boolean;
  onToggleDebug: () => void;
  bigChips: boolean;
  onToggleBigChips: () => void;
  smallAll: boolean;
  onToggleSmallAll: () => void;
}) {
  return (
    <header className="relative w-full h-[218px] text-center flex flex-col items-center justify-end pb-[53px] max-sm:h-auto max-sm:min-h-[180px] max-sm:pt-[60px] max-sm:pb-8">
      <nav className="absolute top-4 right-0 flex items-center gap-4 max-sm:top-3" aria-label="External links">
        {/* Dev-only: hide the hero surface fill to inspect the orbs. Stripped
            from production builds via import.meta.env.DEV. */}
        {import.meta.env.DEV && (
          <button
            type="button"
            onClick={onToggleDebug}
            aria-pressed={debug}
            className={`${iconBtnClass} font-[Roboto_Mono,monospace] text-[11px] ${debug ? 'bg-(--icon-btn-hover) text-(--title-color)' : 'text-(--footer-muted)'}`}
            title="Toggle hero surface fill (dev only)"
          >
            BG
          </button>
        )}
        {import.meta.env.DEV && (
          <button
            type="button"
            onClick={onToggleBigChips}
            aria-pressed={bigChips}
            className={`${iconBtnClass} font-[Roboto_Mono,monospace] text-[11px] ${bigChips ? 'bg-(--icon-btn-hover) text-(--title-color)' : 'text-(--footer-muted)'}`}
            title="Render the small chips as large pills (dev only)"
          >
            LG
          </button>
        )}
        {import.meta.env.DEV && (
          <button
            type="button"
            onClick={onToggleSmallAll}
            aria-pressed={smallAll}
            className={`${iconBtnClass} font-[Roboto_Mono,monospace] text-[11px] ${smallAll ? 'bg-(--icon-btn-hover) text-(--title-color)' : 'text-(--footer-muted)'}`}
            title="Force every pill to the small chip style (dev only)"
          >
            SM
          </button>
        )}
        <a className={iconBtnClass} href="https://github.com/Shrit1401/react-native-thinking-orbs" target="_blank" rel="noopener noreferrer" aria-label="GitHub repository">
          <GitHubIcon />
        </a>
        <a className={iconBtnClass} href="https://x.com/jakubantalik" target="_blank" rel="noopener noreferrer" aria-label="Follow on X (Twitter)">
          <XIcon />
        </a>
      </nav>
      <div className="relative -mt-[190px] -mb-5 cursor-pointer group" aria-hidden="true">
        <img
          className="block relative transition-[filter,transform] duration-500 ease-[cubic-bezier(0.4,0,0.2,1)] will-change-[filter,transform] motion-reduce:!transition-none group-hover:[filter:brightness(1.1)] group-hover:[transform:rotate(8deg)_scale(1.06)]"
          src="/header.png"
          alt=""
          width="146"
          height="117"
          decoding="async"
        />
      </div>
      <h1 className="text-[22px] font-medium leading-[30px] text-(--title-color)">Thinking orbs</h1>
      <p className="text-sm font-normal leading-[21px] text-(--subtitle-color) opacity-50">Animated thinking orb component</p>
    </header>
  );
}
